---
title: "Airports"
output: html_notebook
---

```{r}
library(data.table)
library(tidyverse)
library(openxlsx)

dir <- "C:/Users/CLam/Desktop/trends-airports/Data"

# Enplanements
compile.faa.enplanements <- function() {
  efiles <- list.files(dir, pattern = "-commercial-service-enplanements.xlsx", full.names = T)
  dts <- NULL
  for (efile in efiles) {
    fileyrabr <- basename(efile) %>% str_extract("\\d+")
    fileyr <- fileyrabr %>% paste0("20", .)
    dt <- read.xlsx(efile) %>% as.data.table
    cols <- c(colnames(dt)[1:8], colnames(dt)[grep(fileyrabr, colnames(dt))])
    dtn <- dt[!is.na(Hub), ..cols][, year := fileyr]
    colnames(dtn) <- c("Rank", "RO", "ST", "Locid", "City", "Airportname", "SL", "Hub", "enplanements", "year")
    dtn[, enplanements := as.numeric(enplanements)]
    ifelse(is.null(dts), dts <- dtn, dts <- rbindlist(list(dts, dtn), use.names = T))
  }
  return(dts)
}

compile.faa.enplanement.hub <- function(type) { # options: large or peer
  dts <- compile.faa.enplanements()
  
  if (type == "large") {
    # large hubs
    lghubs <- unique(dts[year == max(year) & Hub == "L", .(RO, ST, Locid)]) # current large hubs data table
    lgdf <- dts[year == max(year) & Hub == "L", select(.SD, Rank:SL)] # current large hub 'template' You can use dplyr methods within data.table!
    dts2 <- copy(dts)
    dtss <- dts2[lghubs, on = c("RO", "ST", "Locid")] # isolate large hubs data
  } else if (type == "peer") {
    plh <- c("DEN", "SFO", "SEA", "CLT", "PHX", "MSP", "BOS", "BWI", "SAN", "TPA", "PDX") # Locid
    plhubs <- unique(dts[year == max(year) & Locid %in% plh, .(RO, ST, Locid)]) # peer large hubs data table
    lgdf <- dts[year == max(year) & Locid %in% plh, select(.SD, Rank:SL)] # current large hub 'template' You can use dplyr methods within data.table!
    dts2 <- copy(dts)
    dtss <- dts2[plhubs, on = c("RO", "ST", "Locid")] # isolate large hubs data
  }
  ldts <- dtss[, lapply(.SD, sum), .SDcols = c("enplanements"), by = .(RO, ST, Locid, year)] # reconcile data
  ldts[lgdf, on = c("RO", "ST", "Locid"), `:=` (Rank = i.Rank, Locid = i.Locid, City = i.City, Airportname = i.Airportname, SL = i.SL)] # join data
  ldtsc <- dcast.data.table(ldts, Rank + RO + ST + Locid + City + Airportname + SL ~ paste0("cy", year), value.var = "enplanements")
  # calculate % change
  cycols <- colnames(ldtsc)[grep("\\d+", colnames(ldtsc))]
  cycols1 <- c(tail(cycols, -1), cycols[length(cycols)])
  cycols2 <- c(head(cycols, -1), "cy2010")
  cyname <- paste0("share_", cycols1, "-", cycols2)
  dtcalc <- ldtsc[, (cyname) := mapply(function(x, y) (.SD[[x]]-.SD[[y]])/.SD[[y]], cycols1, cycols2, SIMPLIFY = F)]
  # calculate ranks for most recent and post-decade % change
  rankcols  <- colnames(dtcalc)[(length(colnames(dtcalc))-1):length(colnames(dtcalc))]
  rankcolsnm <- paste0("rank_", rankcols)
  dtcalcrank <- dtcalc[, (rankcolsnm) := mapply(function(x) rank(-.SD[[x]]), rankcols, SIMPLIFY = F)]
}
```

```{r}
ldt <- compile.faa.enplanement.hub("large")
pldt <- compile.faa.enplanement.hub("peer")
```

```{r}
# option: write to excel file. Run chunk
dtlist <- list(LargeHubs = ldt, PeerLargeHubs = pldt)
enplane.wb <- createWorkbook()
for (d in 1:length(dtlist)) {
  addWorksheet(enplane.wb, names(dtlist)[d])
  modifyBaseFont(enplane.wb, fontSize = 10, fontName = "Segoe UI Semilight")
  pct <- createStyle(numFmt="0%")
  num <- createStyle(numFmt = "#,##0")
  writeData(enplane.wb, names(dtlist)[d], dtlist[[d]])
  addStyle(enplane.wb, names(dtlist)[d], style = pct, cols = str_which(colnames(dtlist[[d]]), "^share_"), rows = c(2:(nrow(dtlist[[d]])+1)), gridExpand = T)
  addStyle(enplane.wb, names(dtlist)[d], style = num, cols = str_which(colnames(dtlist[[d]]), "^cy"), rows = c(2:(nrow(dtlist[[d]])+1)), gridExpand = T, stack = T)
  saveWorkbook(enplane.wb, file = file.path(dir, paste0("PassEnplanementsbyAirport_", Sys.Date(), ".xlsx")), overwrite = T)
}

```


