---
title: "Airports -- SeaTac"
output: html_notebook
---


```{r Functions, include=FALSE}
library(data.table)
library(tidyverse)
library(readxl)
library(plotly)
library(openxlsx)

dir <- "Y:/Perf Trends/Active_Trends/SeaTac_Airport/Data"
# dir <- "C:/Users/clam/Desktop/trends-airports/Data"
# outdir <- "C:/Users/clam/Desktop/trends-airports/Data"

compile.seatac.pco <- function() {
  # current
  efiles <- list.files(dir, pattern = "traf-ops-\\d{6}", full.names = T)
  dts <- NULL
  for (efile in efiles) {
    fname <- basename(efile)
    month.num <- str_extract(fname, "\\d{2}")
    year <- str_extract(fname, "\\d{4}(?=\\.x)")
    dt <- read_excel(efile, skip =3)
    setDT(dt)
    cols <- c("...1", colnames(dt)[str_which(colnames(dt), paste0("^", month.name[as.numeric(month.num)],".*", year))])
    t <- dt[!is.na(get(eval(cols[2]))), ..cols][, `:=` (date = lubridate::ymd(paste(year, month.num, 1)))]
    setnames(t, cols, c("type", "value"))
    t[, type := str_to_lower(type)]
    ifelse(is.null(dts), dts <- t, dts <- rbindlist(list(dts, t), use.names = T))
  }
  # archive 2015-16
  t <- dt <- NULL
  fname <- "traf-ops-2015-2016.xlsx"
  snames <- getSheetNames(file.path(dir, fname))
  ops1 <- snames[str_which(snames, "^Ops.*15")]
  ops2 <- snames[str_which(snames, "^Ops.*(Jan|Feb).*16")]
  allops <- c(ops1, ops2)
  # read-in each spreadsheet
  arc.dts <- NULL
  for (i in 1:length(allops)) {
    month.num <- match(str_extract(allops[i], "(?<=Ops_)\\w{3}"), month.abb)
    year <- paste0("20", str_extract(allops[i], "\\d+$"))

    dt <- read_excel(file.path(dir, fname), sheet = allops[i], skip = 3)
    setDT(dt)
    cols <- c("...1", colnames(dt)[str_which(colnames(dt), paste0("^", month.name[as.numeric(month.num)],".*", year))])
    t <- dt[!is.na(get(eval(cols[2]))), ..cols][, `:=` (date = lubridate::ymd(paste(year, month.num, 1)))]
    setnames(t, cols, c("type", "value"))
    t[, type := str_to_lower(type)]
    t <- t[!is.na(type)]
    ifelse(is.null(arc.dts), arc.dts <- t, arc.dts <- rbindlist(list(arc.dts, t), use.names = T))
  }
  # archive 2014
  t <- dt <- NULL
  arc.dts2 <- NULL
  for (i in 1:length(ops1)) {
    month.num <- match(str_extract(ops1[i], "(?<=Ops_)\\w{3}"), month.abb)
    year <- "2014"
    
    dt <- read_excel(file.path(dir, fname), sheet = ops1[i], skip = 3)
    setDT(dt)
    cols <- c("...1", colnames(dt)[str_which(colnames(dt), paste0("^", month.name[as.numeric(month.num)],".*", year))])
    t <- dt[!is.na(get(eval(cols[2]))), ..cols][, `:=` (date = lubridate::ymd(paste(year, month.num, 1)))]
    setnames(t, cols, c("type", "value"))
    t[, type := str_to_lower(type)]
    t <- t[!is.na(type)]
    ifelse(is.null(arc.dts2), arc.dts2 <- t, arc.dts2 <- rbindlist(list(arc.dts2, t), use.names = T))
    
  }
  alldts <- rbindlist(list(arc.dts2, arc.dts, dts), use.names = T)
  return(alldts)
}

create.seatac.subtable <- function(category = c("all passengers", 
                                                "domestic passengers", 
                                                "international passengers", 
                                                "all cargo", 
                                                "all freight cargo", 
                                                "domestic freight cargo", 
                                                "international freight cargo", 
                                                "mail cargo"), 
                                   totals = c("monthly", "annual")) {
  category.dict <- c("all passengers" = "passenger grand total",
                     "domestic passengers" = "subtotal - domestic passengers",
                     "international passengers" = "subtotal - international passengers",
                     "all cargo" = "cargo grand total",
                     "all freight cargo" = "air freight grand total",
                     "domestic freight cargo" = "subtotal - domestic air freight",
                     "international freight cargo" = "subtotal - international air freight",
                     "mail cargo" = "air mail grand total")
  
  dt <- suppressMessages(compile.seatac.pco())
  type.desc <- category.dict[category]
  
  if (totals == "monthly") {
    t <- dt[type %in% eval(type.desc), lapply(.SD, sum), .SDcols = "value", by = .(type, month(date), year(date))]
    t$month_abr <- factor(month.abb[t$month], levels = month.abb)
    t$year <- factor(t$year, levels = sort(unique(t$year)))
    t <- t[order(year, month)]
  } else {
    t <- dt[type %in% eval(type.desc), lapply(.SD, sum), .SDcols = "value", by = .(type, year(date))]
    t$year <- factor(t$year, levels = sort(unique(t$year)))
    t <- t[order(year)]
  }
  return(t)
}

# cast.tbl.compute.totals <- function(table) {
#   tot <- table[, lapply(.SD, sum), .SDcols = "value", by = year][, month_abr := "Total"]
#   dt <- rbindlist(list(table, tot), use.names = T, fill = T)
#   t <- dcast.data.table(dt, month_abr ~ paste0("cy", year), value.var = "value")
#   setnames(t, "month_abr", "Month")
#   return(t)
# }

# export.seatac.excel <- function() {
#   dt <- compile.seatac.pco()
#   categories <- c("all passengers", "domestic passengers", "international passengers", "all cargo", "all freight cargo", "domestic freight cargo", "international freight cargo", "mail cargo")
#   create.seatac.subtable.monthly <- partial(create.seatac.subtable, totals = "monthly")
#   dtlist <- map(categories, create.seatac.subtable.monthly) %>% map(cast.tbl.compute.totals)
#   names(dtlist) <- lapply(categories, function(x) str_replace_all(x, " ", "_"))
#   newfilenm <- "Airport_Passenger_Cargo_Counts_"
#   wb <- createWorkbook()
#   for (d in 1:length(dtlist)) {
#     addWorksheet(wb, names(dtlist)[d])
#     modifyBaseFont(wb, fontSize = 10, fontName = "Segoe UI Semilight")
#     num <- createStyle(numFmt = "#,##0")
#     writeData(wb, names(dtlist)[d], dtlist[[d]])
#     addStyle(wb, names(dtlist)[d], 
#              style = num, 
#              cols = str_which(colnames(dtlist[[d]]), "^cy\\d+"), 
#              rows = c(2:(nrow(dtlist[[d]])+1)), gridExpand = T, stack = T)
#     # saveWorkbook(wb, file = file.path(dir, paste0(newfilenm, Sys.Date(), ".xlsx")), overwrite = T)
#     saveWorkbook(wb, file = file.path(outdir, paste0(newfilenm, Sys.Date(), ".xlsx")), overwrite = T)
#   }
#   cat("\nData exported to excel\n")
# }

create.monthly.area.chart.by.year <- function(category) {
  dt <- create.seatac.subtable(category, "monthly")
  dt[, year := factor(year, levels = rev(unique(dt$year)))]
  
  # labels
  if (category == "all passengers") category <- "passengers" 
  # unit
  ifelse(category != "passengers", label <- "Metric Tons", label <- "Passengers")
  
  g <- ggplot(dt, aes(x = month_abr, y = value, group = year, fill = year)) +
    geom_area(position = "identity", aes(alpha = .5), show.legend =FALSE) +
    ylab(label) + 
    xlab(str_to_title(category)) +
    scale_y_continuous(labels=scales::comma)

  ggplotly(g)
}

create.barchart.by.month <- function(category) {
  dt <- create.seatac.subtable(category, "monthly")
  t <- dt[, year := as.numeric(as.character(year))
        ][year %in% c((max(year)-1), max(year)), 
          ][, year := factor(year, levels = c((max(dt$year)-1), max(dt$year)))]
  
  # set colors
  mycolors <- c("grey", "purple")
  names(mycolors) <-  levels(t$year)
  
  # labels
  if (category == "all passengers") category <- "passengers" 
  # unit
  ifelse(category != "passengers", label <- "Metric Tons", label <- "Passengers")
  
  g <- ggplot(t, aes(x = month_abr, y = value, color = year, fill = year, group = year)) +
    geom_col(width = .7, position = "dodge") + 
    ylab(label) + 
    xlab(str_to_title(category)) +
    scale_color_manual(values = mycolors) +
    scale_fill_manual(values = mycolors) +
    scale_y_continuous(labels=scales::comma) +
    theme(aspect.ratio = 3/5, 
          axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.title.x = element_text(margin = margin(t = 20, r = 0, b = 0, l = 0)))
  g
}

```


The arguments for visual functions are: "all passengers", "domestic passengers", "international passengers", "all cargo", "all freight cargo", "domestic freight cargo", "international freight cargo", "mail cargo"
```{r Area Chart by Month and Year (ggplotly)} 

create.monthly.area.chart.by.year("all passengers")

```

```{r Barchart by Month and Current/Previous Years}

create.barchart.by.month("all passengers")

```

